version: '2'

services:
  db:
    image: mariadb:10.2
    container_name: basketdb-docker
    ports:
     - "3385:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
    volumes:
     - basketdb_volume:/var/lib/mysql
     - ~/shareDocker:/home/mysql/dataDocker
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  basketdb_volume:
